# 一、Python基础
## 1. 列表推导式与条件赋值

\[\* for i in \*\] 。其中，第一个 * 为映射函数，其输入为后面 i 指代的内容，第二个 * 表示迭代的对象。

In [2]:
def my_func(x):
    return 2*x

[my_func(i) for i in range(5)]
#  

[0, 2, 4, 6, 8]

多层嵌套，如下面的例子中第一个 for 为外层循环，第二个为内层循环。

In [1]:
# 
[m+'_'+n for m in ['a', 'b'] for n in ['c', 'd']]

['a_c', 'a_d', 'b_c', 'b_d']

带有 if 选择的条件赋值，其形式为 value = a if condition else b ：

In [4]:
value = 'cat' if 2>1 else 'dog'
value

'cat'

In [5]:
L = [1, 2, 3, 4, 5, 6, 7]
[i if i <= 5 else 5 for i in L]

[1, 2, 3, 4, 5, 5, 5]

## 2. 匿名函数与map方法

In [6]:
[(lambda x: 2*x)(i) for i in range(5)]

[0, 2, 4, 6, 8]

对于上述的这种列表推导式的匿名函数映射， Python 中提供了 map 函数来完成，它返回的是一个 map 对象，需要通过 list 转为列表：

In [7]:
 list(map(lambda x: 2*x, range(5)))

[0, 2, 4, 6, 8]

In [8]:
list(map(lambda x, y: str(x)+'_'+y, range(5), list('abcde')))

['0_a', '1_b', '2_c', '3_d', '4_e']

## 3. zip对象与enumerate方法

zip函数能够把多个可迭代对象打包成一个元组构成的可迭代对象，它返回了一个 zip 对象，通过 tuple, list 可以得到相应的打包结果。往往会在循环迭代的时候使用到 zip 函数

In [2]:
L1, L2, L3 = list('abc'), list('def'), list('hij')
list(zip(L1, L2, L3))
tuple(zip(L1, L2, L3))

(('a', 'd', 'h'), ('b', 'e', 'i'), ('c', 'f', 'j'))

In [3]:
for i, j, k in zip(L1, L2, L3):
    print(i, j, k)

a d h
b e i
c f j


enumerate 是一种特殊的打包，它可以在迭代时绑定迭代元素的遍历序号：

In [4]:
L = list('abcd')
for index, value in enumerate(L):
    print(index, value)
#等价于
for index, value in zip(range(len(L)), L):
    print(index, value)

0 a
1 b
2 c
3 d
0 a
1 b
2 c
3 d


当需要对两个列表建立字典映射时，可以利用 zip 对象：

In [5]:
dict(zip(L1, L2))

{'a': 'd', 'b': 'e', 'c': 'f'}

In [10]:
zipped = list(zip(L1, L2, L3))
list(zip(*zipped)) # 三个元组分别对应原来的列表

[('a', 'b', 'c'), ('d', 'e', 'f'), ('h', 'i', 'j')]

# 二、Numpy基础
## 1. np数组的构造

In [1]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [2]:
np.linspace(1,5,11) # 起始、终止（包含）、样本个数

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ])

In [3]:
np.arange(1,5,2) # 起始、终止（不包含）、步长

array([1, 3])

In [4]:
np.zeros((2,3)) # 传入元组表示各维度大小

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.eye(3) # 3*3的单位矩阵

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
np.eye(3, k=1) # 偏移主对角线1个单位的伪单位矩阵

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [7]:
np.full((2,3), 10) # 元组传入大小，10表示填充数值

array([[10, 10, 10],
       [10, 10, 10]])

In [8]:
np.full((2,3), [1,2,3]) # 通过传入列表填充每列的值

array([[1, 2, 3],
       [1, 2, 3]])

In [9]:
np.random.rand(3) # 生成服从0-1均匀分布的三个随机数

array([0.09230719, 0.57315589, 0.877449  ])

In [10]:
np.random.rand(3, 3) # 注意这里传入的不是元组，每个维度大小分开输入

array([[0.16887031, 0.8907206 , 0.04617635],
       [0.56018991, 0.25319254, 0.44255096],
       [0.72731668, 0.7768839 , 0.33384165]])

In [11]:
# 对于服从区间 a 到 b 上的均匀分布可以如下生成：
a, b = 5, 15
(b - a) * np.random.rand(3) + a

array([14.42083866, 12.6115327 , 10.94523391])

In [12]:
# randn 生成了 N(0,I) 的标准正态分布：
np.random.randn(2, 2)

array([[0.40119198, 1.48389117],
       [0.92083595, 1.82061058]])

In [13]:
sigma, mu = 2.5, 3
mu + np.random.randn(3) * sigma

array([6.76615333, 5.37477308, 5.27981928])

In [14]:
# randint 可以指定生成随机整数的最小值最大值（不包含）和维度大小
low, high, size = 5, 15, (2,2) # 生成5到14的随机整数
np.random.randint(low, high, size)

array([[11,  8],
       [13,  6]])

In [15]:
# choice 可以从给定的列表中，以一定概率和方式抽取结果，当不指定概率时为均匀采样，默认抽取方式为有放回抽样：
my_list = ['a', 'b', 'c', 'd']
np.random.choice(my_list, 2, replace=False, p=[0.1, 0.7, 0.1 ,0.1])

array(['b', 'd'], dtype='<U1')

In [16]:
np.random.choice(my_list, (3,3))

array([['c', 'c', 'b'],
       ['c', 'a', 'b'],
       ['a', 'a', 'd']], dtype='<U1')

In [17]:
# 当返回的元素个数与原列表相同时，等价于使用 permutation 函数，即打散原列表：
np.random.permutation(my_list)

array(['c', 'b', 'a', 'd'], dtype='<U1')

In [18]:
# 随机种子能够固定随机数的输出结果：
np.random.seed(0)

## 2. np数组的变形与合并

In [19]:
# 转置
np.zeros((2,3)).T

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
# 对于二维数组而言， r_ 和 c_ 分别表示上下合并和左右合并：
np.r_[np.zeros((2,3)),np.zeros((2,3))]

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
# 一维数组和二维数组进行合并时，应当把其视作列向量，在长度匹配的情况下只能够使用左右合并的 c_ 操作：
try:
    np.r_[np.array([0,0]),np.zeros((2,1))]
except Exception as e:
    Err_Msg = e
Err_Msg

ValueError('all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)')

In [22]:
np.r_[np.array([0,0]),np.zeros(2)]

array([0., 0., 0., 0.])

In [23]:
np.c_[np.array([0,0]),np.zeros((2,3))]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
# reshape 能够帮助用户把原数组按照新的维度重新排列。在使用时有两种模式，分别为 C 模式和 F 模式，分别以逐行和逐列的顺序进行填充读取。
target = np.arange(8).reshape(2,4)
target

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [25]:
target.reshape((4,2), order='C') # 按照行读取和填充

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [26]:
target.reshape((4,2), order='F') # 按照列读取和填充

array([[0, 2],
       [4, 6],
       [1, 3],
       [5, 7]])

In [27]:
# 由于被调用数组的大小是确定的， reshape 允许有一个维度存在空缺，此时只需填充-1即可：
target.reshape((4,-1))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [28]:
target = np.ones((3,1))
target.reshape(-1)

array([1., 1., 1.])

## 3. np数组的切片与索引

In [29]:
target = np.arange(9).reshape(3,3)
target[:-1, [0,2]]

array([[0, 2],
       [3, 5]])

利用 np.ix_ 在对应的维度上使用布尔索引，但此时不能使用 slice 切片：

In [30]:
target[np.ix_([True, False, True], [True, False, True])]

array([[0, 2],
       [6, 8]])

In [31]:
target[np.ix_([1,2], [True, False, True])]

array([[3, 5],
       [6, 8]])

当数组维度为1维时，可以直接进行布尔索引，而无需 np.ix_ ：

In [32]:
new = target.reshape(-1)
new[new%2==0]

array([0, 2, 4, 6, 8])

## 4. 常用函数

In [33]:
# where 是一种条件函数，可以指定满足条件与不满足条件位置对应的填充值：
a = np.array([-1,1,-1,0])
np.where(a>0, a, 5)

array([5, 1, 5, 5])

In [34]:
# nonzero 返回非零数的索引， argmax, argmin 分别返回最大和最小数的索引：
a = np.array([-2,-5,0,1,3,-1])
np.nonzero(a)

(array([0, 1, 3, 4, 5], dtype=int64),)

In [35]:
# any 指当序列至少 存在一个 True 或非零元素时返回 True ，否则返回 False
np.any([[True, False], [False, False]], axis=0)

array([ True, False])

In [36]:
# all 指当序列元素 全为 True 或非零元素时返回 True ，否则返回 False
a = np.array([0,1])
a.all()

False

cumprod, cumsum 分别表示累乘和累加函数，返回同长度的数组， diff 表示和前一个元素做差，由于第一个元素为缺失值，因此在默认参数情况下，返回长度是原数组减1

In [37]:
a = np.array([1,2,3])
print(a.cumprod())
print(a.cumsum())
print(np.diff(a))

[1 2 6]
[1 3 6]
[1 1]


常用的统计函数包括 max, min, mean, median, std, var, sum, quantile ，其中分位数计算是全局方法，因此不能通过 array.quantile 的方法调用：

但是对于含有缺失值的数组，它们返回的结果也是缺失值，如果需要略过缺失值，必须使用 nan\* 类型的函数，上述的几个统计函数都有对应的 nan\* 函数。

In [38]:
target = np.array([1, 2, np.nan])
np.nanmax(target)

2.0

## 5. 广播机制

当一个标量和数组进行运算时，标量会自动把大小扩充为数组大小，之后进行逐元素操作。

当两个数组维度完全一致时，使用对应元素的操作，否则会报错，除非其中的某个数组的维度是 m×1 或者 1×n ，那么会扩充其具有 1 的维度为另一个数组对应维度的大小。例如， 1×2 数组和 3×2 数组做逐元素运算时会把第一个数组扩充为 3×2 ，扩充时的对应数值进行赋值。但是，需要注意的是，如果第一个数组的维度是 1×3 ，那么由于在第二维上的大小不匹配且不为 1 ，此时报错。

In [40]:
res = np.ones((3,2))
print(res * np.array([[2,3]])) # 扩充第一维度为3
print(res * np.array([[2],[3],[4]])) # 扩充第二维度为2
print(res * np.array([[2]])) # 等价于两次扩充

[[2. 3.]
 [2. 3.]
 [2. 3.]]
[[2. 2.]
 [3. 3.]
 [4. 4.]]
[[2. 2.]
 [2. 2.]
 [2. 2.]]


当一维数组 Ak 与二维数组 Bm,n 操作时，等价于把一维数组视作 A1,k 的二维数组，使用的广播法则同上，当 k!=n 且 k,n 都不是 1 时报错。

In [42]:
print(np.ones(3) + np.ones((2,3)))

[[2. 2. 2.]
 [2. 2. 2.]]


## 6. 向量与矩阵的计算

In [43]:
a = np.array([1,2,3])
b = np.array([1,3,5])
a.dot(b)

22

In [44]:
martix_target =  np.arange(4).reshape(-1,2)
np.linalg.norm(martix_target, 'fro')

3.7416573867739413

In [45]:
a = np.arange(4).reshape(-1,2)
b = np.arange(-4,0).reshape(-1,2)
a@b

array([[ -2,  -1],
       [-14,  -9]])